// Function Index:
void initFile ();
void printScore ();
void saveHigh ();


/* Function: initScoreFile
 * --------------
 * Checks if there's a score file, if not, creates one.
 */
void initScoreFile () {

  FILE *file;
  file = fopen("score.dat", "rb+");

  if (file == NULL) {
    //fclose(file);
    file = fopen("score.dat", "wb+");

  }

  fclose(file);
}

/* Function: printScore
 * --------------
 * Get score from file and prints it.
 */
void printScore() {

  FILE *file;
  file = fopen("score.dat", "ab+");

  int scanner = 0;
  fread(&scanner, sizeof(int), 1, file);

  printf(BWHT "\t\t\t2048 - SCORE\n\n");
  printf(BGRN "\t\t      HIGH SCORE: %d \n\n" RESET, scanner);
  printf(BWHT "\t   Combine to earn it\'s combination in points!\n");
  printf("\t  Make " BGRN);
  printf("2048" BWHT);
  printf(" to unlock 2x score multiplier bonus!\n\n\n" RESET);

  fclose(file);

}

/* Function: saveHigh
 * --------------
 * Get score from file and compare with a new value. If that value is higher
 * than previous score it is replaced with the value.
 *
 * score: value generated by the game.
 */
void saveHigh(int score) {

  FILE *file;
  file = fopen("score.dat", "rb+");

  int high = 0;
  fread(&high, sizeof(int), 1, file);
  rewind(file);

  if (score > high) {
    fwrite((const void*) & score, sizeof(int), 1 , file);
    
  }

  fclose(file);
}
